[book]
title = "呂學洲"
authors = ["呂學洲"]
description = "各種紀錄和連結"
src = "src"
language = "zh-TW"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url= "https://github.com/evan361425/evan361425.github.io"
git-branch="master"
preferred-dark-theme = "rust"
mathjax-support = true
google-analytics = "G-P67FD9XP83"
no-section-label = true
additional-css = ["style.css", "pagetoc.css"]
additional-js = ["pagetoc.js", "mermaid-init.js"]
edit-url-template = "https://github.com/evan361425/evan361425.github.io/edit/master/{path}"
[output.html.fold]
enable = true
[output.html.print]
enable = false

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
[preprocessor.plantuml]
plantuml-cmd="http://www.plantuml.com/plantuml"
