site_name: 心得與記錄
site_url: https://evan361425.github.io/
site_description: 各種紀錄和心得
docs_dir: src/
repo_name: GitHub
repo_url: https://github.com/evan361425/evan361425.github.io
edit_uri: https://github.com/evan361425/evan361425.github.io/edit/master/src

nav:
  - index.md
  - 開源專案: projects/index.md
  - 讀書心得:
      - 目錄: feedback/index.md
      - "[寫作中] Designing Data-intensive Applications":
          - 簡介: feedback/designing-data-intensive-applications/introduction.md
          - 資料模型和語法: feedback/designing-data-intensive-applications/data-model.md
          - 索引: feedback/designing-data-intensive-applications/db-index.md
          - 資料倉儲: feedback/designing-data-intensive-applications/analytic-db.md
          - 編碼和進程: feedback/designing-data-intensive-applications/encoding-evolution.md
          - 處理競賽情況: feedback/designing-data-intensive-applications/resolve-race-condition.md
      - Distributed Systems with Node.js:
          - 簡介: feedback/distributed-systems-with-node.js/introduction.md
          - 協定: feedback/distributed-systems-with-node.js/protocol.md
          - SLA 和負載測試: feedback/distributed-systems-with-node.js/sla-and-load-testing.md
          - 可觀測性: feedback/distributed-systems-with-node.js/observability.md
          - 容器化: feedback/distributed-systems-with-node.js/container.md
          - 容器調度工具和其他: feedback/distributed-systems-with-node.js/container-orchestration-and-misc.md
  - 隨筆:
      - 簡介: essay/index.md
      - 系統架構類:
          - 如何製作 Docker Container: essay/architecture/made-container.md
          - 建置 PKI 注意事項: essay/architecture/pki-checklist.md
          - 取代 Docker Desktop: essay/architecture/replace-docker-desktop.md
          - Tomcat 的 max_packet_size: essay/architecture/tomcat-max-packet-size.md
      - 程式語言類:
          - Node.js 最佳實作: essay/code/node.js-best-practice.md
          - Node.js 的錯誤有哪些: essay/code/node.js-error.md
      - Vault:
          - 介紹: essay/vault/introduction.md
          - 實作: essay/vault/implementation.md
          - PKI: essay/vault/engine-pki.md
          - Transit: essay/vault/engine-transit.md
      - 網路相關:
          - NTP: essay/web/ntp.md
          - Retry 的策略: essay/web/retry-strategy.md
          - TCP: essay/web/tcp.md
          - URL 長什麼樣子: essay/web/url-structure.md
      - 網路安全:
          - CORS: essay/web-security/cross-origin-resources-sharing.md
          - Mixed Content: essay/web-security/mixed-content.md
          - OWASP API Top 10: essay/web-security/owasp-api-top10.md
          - OWASP 驗證機制最佳指南: essay/web-security/owasp-authentication-best-practice.md
          - OWASP 行動裝置風險: essay/web-security/owasp-mobile-risk-top10.md
      - 其他:
          - 問卷設計指南: essay/questionnaire-principal.md

theme:
  name: material
  language: "zh-TW"
  features:
    - search.suggest
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: 黑夜降臨
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: 白日昇起

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      #make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          # disable-lint
          format: !!python/name:evan361425.fence_mermaid
  - pymdownx.arithmatex:
      generic: true
  # 允許增加 tooltip，於 MD 檔下方中增加下列說明
  # *[Text]: Description
  - abbr
  # 允許設定警告卡片
  # !!! [note|abstract|info|tip|success|question|warning|failure|bug|example|quote|danger] "Custom title"
  - admonition
  # 設定腳註
  # [^1]: Description
  - footnotes
  # 可以設定 attribute，主要用於照片 align
  - attr_list

plugins:
  - git-revision-date
  - search
  - figcaption
  # Use it if need to glob
  # - awesome-pages
  - mermaid

extra:
  analytics:
    provider: google
    property: G-P67FD9XP83

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
