site_name: 心得與記錄
site_url: https://evan361425.github.io/
site_description: 各種紀錄和心得
docs_dir: src/
repo_name: GitHub
repo_url: https://github.com/evan361425/evan361425.github.io
edit_uri: https://github.com/evan361425/evan361425.github.io/edit/master/src

nav:
  - index.md
  - 心得:
      - 目錄: feedback/index.md
      - Designing Data-intensive Applications:
          - 簡介: feedback/designing-data-intensive-applications/index.md
          - 基礎—模型和語法: feedback/designing-data-intensive-applications/foundation-model.md
          - 基礎—索引: feedback/designing-data-intensive-applications/foundation-index.md
          - 基礎—資料倉儲: feedback/designing-data-intensive-applications/foundation-dw.md
          - 基礎—編碼和進程: feedback/designing-data-intensive-applications/foundation-encode.md
          - 基礎—容錯: feedback/designing-data-intensive-applications/foundation-ft.md
          - 分散式—複製: feedback/designing-data-intensive-applications/distributed-replication.md
          - 分散式—分區: feedback/designing-data-intensive-applications/distributed-partition.md
          - 分散式—環境: feedback/designing-data-intensive-applications/distributed-env.md
          - 分散式—容錯: feedback/designing-data-intensive-applications/distributed-ft.md
          - 衍生—批次處理: feedback/designing-data-intensive-applications/derived-batch.md
          - 衍生—串流處理: feedback/designing-data-intensive-applications/derived-stream.md
          - 總結和整合: feedback/designing-data-intensive-applications/farewell.md
          - 詞彙表: feedback/designing-data-intensive-applications/glossary.md
      - Distributed Systems with Node.js:
          - 簡介: feedback/distributed-systems-with-node.js/index.md
          - 協定: feedback/distributed-systems-with-node.js/protocol.md
          - SLA 和負載測試: feedback/distributed-systems-with-node.js/sla-and-load-testing.md
          - 可觀測性: feedback/distributed-systems-with-node.js/observability.md
          - 容器化: feedback/distributed-systems-with-node.js/container.md
          - 容器調度工具和其他: feedback/distributed-systems-with-node.js/container-orchestration-and-misc.md
      - Future Of Fusion Energy[寫作中]:
          - 簡介: feedback/future-of-fusion-energy/index.md
          - 能源: feedback/future-of-fusion-energy/energy.md
          - 核融合: feedback/future-of-fusion-energy/fusion.md
      - Adaptive Concurrency: feedback/adaptive-concurrency.md
      - 狹義相對論[寫作中]: feedback/special-relativity.md
  - 隨筆:
      - 簡介: essay/index.md
      - 系統架構類:
          - 如何製作 Docker Container: essay/architecture/made-container.md
          - 建置 PKI 注意事項: essay/architecture/pki-checklist.md
          - 取代 Docker Desktop: essay/architecture/replace-docker-desktop.md
          - Tomcat 的 max_packet_size: essay/architecture/tomcat-max-packet-size.md
      - 程式語言類:
          - Node.js 最佳實作: essay/code/node.js-best-practice.md
          - Node.js 的錯誤有哪些: essay/code/node.js-error.md
          - 物件導向名詞: essay/code/object-oriented-terms.md
      - 網路相關:
          - 網路怎麼傳: essay/web/network-routing.md
          - 網路傳了什麼: essay/web/network-details.md
          - TCP: essay/web/tcp.md
          - NTP: essay/web/ntp.md
          - Retry 的策略: essay/web/retry-strategy.md
          - Certificate Transparency: essay/web/certificate-transparency.md
          - URL 長什麼樣子: essay/web/url-structure.md
      - 網路安全:
          - CORS: essay/web-security/cross-origin-resources-sharing.md
          - Mixed Content: essay/web-security/mixed-content.md
          - OWASP API Top 10: essay/web-security/owasp-api-top10.md
          - OWASP 驗證機制最佳指南: essay/web-security/owasp-authentication-best-practice.md
          - OWASP 行動裝置風險: essay/web-security/owasp-mobile-risk-top10.md
      - 其他:
          - GPL 的檢查: essay/gpl-check.md
          - 問卷設計指南: essay/questionnaire-principal.md

theme:
  name: material
  language: "zh-TW"
  custom_dir: overrides
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: 黑夜降臨
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: 白日昇起

markdown_extensions:
  # 展開用：??? info "title"
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
  # MathJax
  - pymdownx.arithmatex:
      generic: true
  # 允許安插其他文件到文件中
  - pymdownx.snippets
  - toc:
      # 增加 anchor
      permalink: true
      toc_depth: 3
  # 允許增加 tooltip，於 MD 檔下方中增加下列說明
  # *[Text]: Description
  - abbr
  # 允許設定警告卡片
  # !!! [note|abstract|info|tip|success|question|warning|failure|bug|example|quote|danger] "Custom title"
  - admonition
  # 設定腳註
  # [^1]: Description
  - footnotes
  # 可以設定 attribute，主要用於照片 align
  - attr_list

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      locale: zh
      exclude:
        - index.md
  - search
  - figcaption
  - tablecaption
  - serve_simple
  # Use it if need to glob
  # - awesome-pages

extra:
  analytics:
    provider: google
    property: G-P67FD9XP83
  social:
    - icon: material/file-document
      link: https://evan361425.github.io/flutter-pos-system/PRIVACY_POLICY/
      name: Privacy Policy

extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/custom.js
  # MathJax
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # Zoom images
  - https://cdnjs.cloudflare.com/ajax/libs/medium-zoom/1.0.6/medium-zoom.min.js
