site_name: 心得與記錄
site_url: https://evan361425.github.io/
site_description: 各種紀錄和心得
docs_dir: src/
repo_name: GitHub
repo_url: https://github.com/evan361425/evan361425.github.io
edit_uri: blob/master/src/

# 避免把一些髒東西帶進網站，例如 .gitignore，但是我需要 .well-known 的資料
exclude_docs: |
  !.well-known

_articles:
  essay: &_essay
  - essay
  - essay/architecture
  - essay/code
  - essay/web
  - essay/web-security
  feedback: &_feedback
  - feedback
  - feedback/apple-intelligence
  - feedback/designing-data-intensive-applications
  - feedback/distributed-systems-with-node.js
  - feedback/future-of-fusion-energy
  - feedback/physics
  # WIP:
  #- feedback/site-reliability-workbook

nav:
- index.md
- 心得:
  - 目錄: feedback/index.md
  - Designing Data-intensive Applications:
    - feedback/designing-data-intensive-applications/index.md
    - 基礎—模型和語法: feedback/designing-data-intensive-applications/foundation-model.md
    - 基礎—索引: feedback/designing-data-intensive-applications/foundation-index.md
    - 基礎—資料倉儲: feedback/designing-data-intensive-applications/foundation-dw.md
    - 基礎—編碼和進程: feedback/designing-data-intensive-applications/foundation-encode.md
    - 基礎—容錯: feedback/designing-data-intensive-applications/foundation-ft.md
    - 分散式—複製: feedback/designing-data-intensive-applications/distributed-replication.md
    - 分散式—分區: feedback/designing-data-intensive-applications/distributed-partition.md
    - 分散式—環境: feedback/designing-data-intensive-applications/distributed-env.md
    - 分散式—容錯: feedback/designing-data-intensive-applications/distributed-ft.md
    - 衍生—批次處理: feedback/designing-data-intensive-applications/derived-batch.md
    - 衍生—串流處理: feedback/designing-data-intensive-applications/derived-stream.md
    - 總結和整合: feedback/designing-data-intensive-applications/farewell.md
    - 詞彙表: feedback/designing-data-intensive-applications/glossary.md
  - Distributed Systems with Node.js:
    - feedback/distributed-systems-with-node.js/index.md
    - 協定: feedback/distributed-systems-with-node.js/protocol.md
    - SLA 和負載測試: feedback/distributed-systems-with-node.js/sla-and-load-testing.md
    - 可觀測性: feedback/distributed-systems-with-node.js/observability.md
    - 容器化: feedback/distributed-systems-with-node.js/container.md
    - 容器調度工具和其他: feedback/distributed-systems-with-node.js/container-orchestration-and-misc.md
  - （WIP）Future Of Fusion Energy:
    - feedback/future-of-fusion-energy/index.md
    - 能源: feedback/future-of-fusion-energy/energy.md
    - 核融合: feedback/future-of-fusion-energy/fusion.md
  - （WIP）SRE Workbook:
    - feedback/site-reliability-workbook/index.md
    - 勞動力: feedback/site-reliability-workbook/toil.md
    - 簡化系統: feedback/site-reliability-workbook/simplicity.md
    - 待命小組: feedback/site-reliability-workbook/on-call.md
    - 災難管理: feedback/site-reliability-workbook/incident-response.md
    - 事後析誤文化: feedback/site-reliability-workbook/postmortem-culture.md
    - 負載管理: feedback/site-reliability-workbook/managing-load.md
    - 非抽象大型系統設計: feedback/site-reliability-workbook/nalsd.md
    - 資料管線設計: feedback/site-reliability-workbook/data-pipelines.md
    - 設定檔的最佳實踐: feedback/site-reliability-workbook/configuration-best-practice.md
    - 金絲雀部署: feedback/site-reliability-workbook/canary-release.md
  - Release It!: feedback/release-it.md
  - Adaptive Concurrency: feedback/adaptive-concurrency.md
  - Physics:
    - feedback/physics/index.md
    - 天文學: feedback/physics/astronomy.md
    - （WIP）狹義相對論: feedback/physics/special-relativity.md
  - Apple Private Cloud Computing:
    - feedback/apple-intelligence/index.md
    - 目標和信任基礎: feedback/apple-intelligence/ability.md
- 年度回顧:
  - review/index.md
  - 2022 AI 回顧: review/2022-ai.md
  - 2023 回顧: review/2023.md
  - 2024 回顧: review/2024.md
- 隨筆:
  - essay/index.md
  - 系統架構類:
    - 如何製作 Docker Container: essay/architecture/made-container.md
    - 建置 PKI 注意事項: essay/architecture/pki-checklist.md
    - 取代 Docker Desktop: essay/architecture/replace-docker-desktop.md
    - Tomcat 的 max_packet_size: essay/architecture/tomcat-max-packet-size.md
    - TCP socket 連線被清除的錯誤排查: essay/architecture/tcp-socket-loss-after-dhcp.md
  - 程式語言類:
    - Node.js 最佳實作: essay/code/node.js-best-practice.md
    - Node.js 的錯誤有哪些: essay/code/node.js-error.md
    - 物件導向名詞: essay/code/object-oriented-terms.md
    - 處理舊有系統: essay/code/handle-legacy-system.md
  - 網路相關:
    - 網路怎麼傳: essay/web/network-routing.md
    - 網路傳了什麼: essay/web/network-details.md
    - 網路推薦書籍: essay/web/network-books.md
    - TCP: essay/web/tcp.md
    - NTP: essay/web/ntp.md
    - HTTP: essay/web/http.md
    - Retry 的策略: essay/web/retry-strategy.md
    - Certificate Transparency: essay/web/certificate-transparency.md
    - URL 長什麼樣子: essay/web/url-structure.md
    - Maglev: essay/web/maglev.md
  - 網路安全:
    - CORS: essay/web-security/cross-origin-resources-sharing.md
    - Mixed Content: essay/web-security/mixed-content.md
    - OWASP API Top 10: essay/web-security/owasp-api-top10.md
    - OWASP 驗證機制最佳指南: essay/web-security/owasp-authentication-best-practice.md
    - OWASP 行動裝置風險: essay/web-security/owasp-mobile-risk-top10.md
  - 其他:
    - GPL 的檢查: essay/gpl-check.md
    - Nginx 1.18 到 1.22 的差異: essay/nginx-changelog.md
    - Node.js 14 到 18 的差異: essay/node-changelog-14-18.md
    - 問卷設計指南: essay/questionnaire-principal.md
    - 開發體驗的改進: essay/devex-in-action.md
    - 面試時的殺手級問題: essay/interview-questions.md
  - PLS-SEM: essay/pls-sem.md
  - 機密運算: essay/confidential-computing.md
theme:
  name: material
  language: "zh-TW"
  custom_dir: overrides
  font:
    text: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Helvetica, Roboto, Arial, "PingFang TC", "Microsoft JhengHei", "微軟正黑", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
  icon:
    edit: material/file-eye
  features:
  - search.suggest
  - search.highlight
  - navigation.top
  - navigation.tabs
  - navigation.indexes
  - navigation.footer
  - content.code.annotate
  - content.code.copy
  - content.action.edit
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: light-blue
    toggle:
      icon: material/weather-sunny
      name: 黑夜降臨
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue-grey
    accent: deep orange
    toggle:
      icon: material/weather-night
      name: 白日昇起

markdown_extensions:
# 展開用：??? info "title"
- pymdownx.details
# Code block highlight
- pymdownx.highlight
# Code block allow nested
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
# MathJax
- pymdownx.arithmatex:
    generic: true
# 允許安插其他文件到文件中
- pymdownx.snippets
- toc:
    # 增加 anchor
    permalink: true
    toc_depth: 3
    # 重新命名
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
# 允許增加 tooltip，於 MD 檔下方中增加下列說明
# *[Text]: Description
- abbr
# 允許設定警告卡片
# !!! [note|abstract|info|tip|success|question|warning|failure|bug|example|quote|danger] "Custom title"
- admonition
# 設定腳註
# [^1]: Description
- footnotes
# 可以設定 attribute，主要用於照片 align
- attr_list
# 允許 nested links，詳見：https://github.com/mkdocs/mkdocs/issues/545
- mdx_truly_sane_lists

plugins:
# 提供 reproducible build
- info:
    enabled: false
- git-revision-date-localized:
    enable_creation_date: true
    timezone: Asia/Taipei
    locale: zh
    exclude:
    - index.md
- search
- figcaption
- tablecaption
- serve_simple:
    dest: site
    targets:
    - index.md
    - javascripts/
    - stylesheets/
    - feedback/index.md
    - essay/index.md
    - essay/confidential-computing.md
# 用來注入最新的修改
- blogging:
    # https://github.com/liang2kl/mkdocs-blogging-plugin
    # 他會使用 UTC，所以乾脆不要顯示時間，只顯示日期
    time_format: "%Y年%m月%d日"
    dirs: *_essay
    size: 3
    paging: false
    sort:
      by: revision
    categories:
    - name: essay
      dirs: *_essay
      size: 5
      paging: false
      sort:
        by: revision
    - name: feedback
      dirs: *_feedback
      size: 5
      paging: false
      sort:
        by: revision

extra:
  analytics:
    provider: google
    property: G-P67FD9XP83
extra_css:
- stylesheets/custom.css
extra_javascript:
- javascripts/custom.js
# MathJax
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# Zoom images
- https://cdnjs.cloudflare.com/ajax/libs/medium-zoom/1.1.0/medium-zoom.min.js
