name: github pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"

jobs:
  deploy:
    name: GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Copy from https://github.com/roapi/docs/blob/main/.github/workflows/deploy.yml
      # - name: Install mdbook
      #   run: |
      #     curl -sL https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz | tar xzv
      #
      # - name: Install mdbook-open-on-gh
      #   run: |
      #     curl -sL https://github.com/badboy/mdbook-open-on-gh/releases/download/2.0.0/mdbook-open-on-gh-2.0.0-x86_64-unknown-linux-gnu.tar.gz | tar zxv
      # TODO: switch back to download from release after
      # https://github.com/badboy/mdbook-open-on-gh/pull/3 gets released
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install mdbook-open-on-gh
        run: |
          cargo install --git https://github.com/houqp/mdbook-open-on-gh --branch main
          cargo install --git https://github.com/houqp/mdBook --branch ga mdbook
      - name: Install mdbook-mermaid
        uses: engineerd/configurator@v0.0.8
        with:
          name: mdbook-mermaid
          url: https://github.com/badboy/mdbook-mermaid/releases/download/v0.8.3/mdbook-mermaid-v0.8.3-x86_64-unknown-linux-gnu.tar.gz
          pathInArchive: "mdbook-mermaid"
      - name: Build
        run: |
          export PATH=$PATH:$(pwd)
          mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
