name: github pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
  pull_request:

jobs:
  deploy:
    name: GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Copy from https://github.com/roapi/docs/blob/main/.github/workflows/deploy.yml
      - uses: actions-rs/toolchain@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          toolchain: stable
      # TODO: switch back to download from release after
      - name: Install mdbook for master (wait for GA upgrade)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          cargo install --git https://github.com/houqp/mdBook --branch ga mdbook

      - name: Install mdbook for PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Install mdbook-mermaid
        uses: engineerd/configurator@v0.0.8
        with:
          name: mdbook-mermaid
          url: https://github.com/badboy/mdbook-mermaid/releases/download/v0.8.3/mdbook-mermaid-v0.8.3-x86_64-unknown-linux-gnu.tar.gz
          pathInArchive: "mdbook-mermaid"

      - name: Build
        run: |
          export PATH=$PATH:$(pwd)
          mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
