name: github pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Setup mdBook mermaid
        uses: engineerd/configurator@v0.0.8
        with:
          name: mdbook-mermaid
          url: https://github.com/badboy/mdbook-mermaid/releases/download/v0.8.3/mdbook-mermaid-v0.8.3-x86_64-unknown-linux-gnu.tar.gz
          pathInArchive: "mdbook-mermaid"

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
